name: Deploy to AWS

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'bootstrap*.sh'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::327152655879:role/my-bedrock-proxy-github-actions-role
        aws-region: us-east-1
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ~1.7
        
    - name: Terraform Init
      run: |
        cd infra
        terraform init
        
    - name: Terraform Plan
      run: |
        cd infra
        terraform plan -out=tfplan
        
    - name: Terraform Apply
      run: |
        cd infra
        terraform apply -auto-approve tfplan
        
    - name: Get App Runner URL
      id: app-runner
      run: |
        cd infra
        APP_URL=$(terraform output -raw app_runner_url)
        echo "APP_URL=$APP_URL" >> $GITHUB_OUTPUT
        echo "App Runner URL: $APP_URL"
        
    - name: Wait for deployment
      run: |
        echo "Waiting 60 seconds for App Runner service to be ready..."
        sleep 60
        
    - name: Set up Python for smoke tests
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests
        
    - name: Run smoke tests
      env:
        APP_URL: ${{ steps.app-runner.outputs.APP_URL }}
      run: |
        pytest tests/test_smoke.py -v --tb=short
        
    - name: Output deployment info
      run: |
        cd infra
        echo "## 🚀 Deployment Successful" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**App Runner URL:** $(terraform output -raw app_runner_url)" >> $GITHUB_STEP_SUMMARY
        echo "**Datadog Dashboard:** $(terraform output -raw dashboard_url)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Monitors Created:" >> $GITHUB_STEP_SUMMARY
        echo "- High Latency Monitor ID: $(terraform output -raw high_latency_monitor_id)" >> $GITHUB_STEP_SUMMARY
        echo "- High Error Rate Monitor ID: $(terraform output -raw high_error_rate_monitor_id)" >> $GITHUB_STEP_SUMMARY