name: Test OIDC Connection

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::327152655879:role/my-bedrock-proxy-github-actions-role
        aws-region: us-east-1
        
    - name: Test AWS Connection
      run: |
        echo "Testing AWS connection..."
        aws sts get-caller-identity
        echo "✅ OIDC connection successful!"
        
    - name: Check Bedrock Access
      run: |
        echo "Testing Bedrock access..."
        aws bedrock list-foundation-models --region us-east-1 --max-results 1 || echo "⚠️  Bedrock access might need additional setup"